import {
  User,
  Project,
  TaskItem,
  MeetingItem,
  DeliverableItem,
  Invoice,
  ClientContact,
  TransactionItem,
  RecentActivityItem,
  AppNotification,
  ReminderItem,
} from '@/types';

export const INITIAL_COMPANY_USER: User = {
  id: 'usr_isaacify_company',
  name: 'ISAACIFY Agency',
  firstName: 'Abhilash',
  email: 'isaacify.info@gmail.com',
  role: 'team',
  teamRole: 'owner',
  workspaceId: 'ws_isaacify',
  workspaceName: 'ISAACIFY Studios',
  agencyName: 'ISAACIFY Creative',
  agencyLead: 'Abhilash V',
  currency: 'LKR',
  reducedMotion: false,
  notificationsEnabled: true,
};

export const INITIAL_FREELANCER_USER: User = {
  id: 'usr_kasun',
  name: 'Kasun Perera',
  firstName: 'Kasun',
  email: 'kasun@isaacify.io',
  role: 'freelancer',
  workspaceId: 'ws_isaacify',
  workspaceName: 'ISAACIFY Creative',
  agencyName: 'ISAACIFY Creative',
  agencyLead: 'Kasun Perera',
  currency: 'LKR',
  reducedMotion: false,
  notificationsEnabled: true,
};

export const INITIAL_CLIENT_USER: User = {
  id: 'usr_senuri_client',
  clientId: 'cl_senuri',
  name: 'Senuri Perera',
  firstName: 'Senuri',
  email: 'senuri@ceylonbites.lk',
  role: 'client',
  workspaceId: 'ws_isaacify',
  workspaceName: 'CeylonBites Workspace',
  agencyName: 'ISAACIFY Creative',
  agencyLead: 'Kasun Perera',
  currency: 'LKR',
  reducedMotion: false,
  notificationsEnabled: true,
};

export const INITIAL_CLIENTS: ClientContact[] = [
  {
    id: 'cl_senuri',
    workspaceId: 'ws_isaacify',
    name: 'Senuri Perera',
    companyName: 'CeylonBites Spices',
    email: 'senuri@ceylonbites.lk',
    phone: '+94 77 123 4567',
    status: 'active',
    isArchived: false,
    linkedUserId: 'usr_senuri_client',
    outstandingBalance: 108000,
    internalNotes: 'Key client for Q4 spice brand launch and direct export e-commerce.',
  },
  {
    id: 'cl_harbor',
    workspaceId: 'ws_isaacify',
    name: 'David Lee',
    companyName: 'Harbor Studio',
    email: 'david@harborstudio.com',
    phone: '+94 71 987 6543',
    status: 'active',
    isArchived: false,
    outstandingBalance: 140000,
    internalNotes: 'Architectural portfolio website and 3D showroom render integration.',
  },
  {
    id: 'cl_bloom',
    workspaceId: 'ws_isaacify',
    name: 'Amara Fernando',
    companyName: 'Bloom Creative',
    email: 'amara@bloomcreative.lk',
    phone: '+94 76 555 4321',
    status: 'active',
    isArchived: false,
    outstandingBalance: 0,
    internalNotes: 'Sustainable fashion retail catalog and marketing collaterals.',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_ceylonbites',
    workspaceId: 'ws_isaacify',
    title: 'CeylonBites Brand & Website',
    clientId: 'cl_senuri',
    clientName: 'Senuri Perera',
    clientInitials: 'CB',
    status: 'In Progress',
    progressPercentage: 60,
    totalTasks: 10,
    completedTasks: 6,
    currentMilestone: 'Milestone 2 of 4',
    milestoneRatio: '2/4',
    dueDate: '30 Sep 2026',
    startDate: '01 Sep 2026',
    budget: 180000,
    currency: 'LKR',
    priority: 'High',
    daysLeftText: '4 days left',
    currentFocus: 'Homepage review',
    scopeNotes: 'Complete rebranding, responsive UX/UI design (10 screens), spice shop e-commerce flows, payment gateway specs.',
    revisionLimit: 3,
    usedRevisions: 1,
    assignedTeam: ['usr_kasun', 'usr_isaacify_company'],
    milestones: [
      {
        id: 'ms_cb_1',
        title: 'Brand Identity & Visual System',
        description: 'Color palette, logo variations, typography, spice icon pack',
        dueDate: '10 Sep 2026',
        status: 'approved',
        order: 1,
        amount: 50000,
      },
      {
        id: 'ms_cb_2',
        title: 'E-Commerce Wireframes & High-Fi UX',
        description: 'Homepage, catalog, product card, shopping cart, checkout',
        dueDate: '30 Sep 2026',
        status: 'client_review',
        order: 2,
        amount: 60000,
        deliverableId: 'del_homepage_v2',
      },
      {
        id: 'ms_cb_3',
        title: 'Frontend Prototype & Responsive Testing',
        description: 'Interactive Figma prototype with mobile breakpoint parity',
        dueDate: '15 Oct 2026',
        status: 'in_progress',
        order: 3,
        amount: 40000,
      },
      {
        id: 'ms_cb_4',
        title: 'Design Assets & Production Handover',
        description: 'Developer specs, exported SVG assets, design tokens',
        dueDate: '30 Oct 2026',
        status: 'pending',
        order: 4,
        amount: 30000,
      },
    ],
    terms: [
      {
        id: 'trm_1',
        title: 'Scope & Revision Limit',
        clause: 'The agreement covers up to 3 major revision rounds per milestone deliverable. Additional changes billed at LKR 7,500/hr.',
        category: 'Scope & Revisions',
        isStandard: true,
      },
      {
        id: 'trm_2',
        title: 'Payment Schedule & Release',
        clause: '40% upfront deposit upon contract signing. Remaining balance released upon Milestone 2 approval and final design handover.',
        category: 'Payment & Late Fees',
        isStandard: true,
      },
      {
        id: 'trm_3',
        title: 'Intellectual Property Rights',
        clause: 'Full copyright and design ownership transfers to CeylonBites Spices upon full invoice settlement.',
        category: 'Intellectual Property',
        isStandard: true,
      },
    ],
    scopeChanges: [
      {
        id: 'sc_1',
        requestedBy: 'Senuri Perera',
        description: 'Add multi-currency selector for UK & Australian export customers.',
        additionalBudget: 25000,
        additionalDays: 3,
        status: 'pending',
        createdAt: '2026-09-22T08:00:00Z',
      },
    ],
  },
  {
    id: 'prj_harbor',
    workspaceId: 'ws_isaacify',
    title: 'Harbor Studio Website',
    clientId: 'cl_harbor',
    clientName: 'David Lee',
    clientInitials: 'HS',
    status: 'In Progress',
    progressPercentage: 45,
    totalTasks: 8,
    completedTasks: 4,
    currentMilestone: 'Milestone 1 of 3',
    milestoneRatio: '1/3',
    dueDate: '15 Oct 2026',
    startDate: '10 Sep 2026',
    budget: 220000,
    currency: 'LKR',
    priority: 'Medium',
    daysLeftText: '18 days left',
    currentFocus: 'Design system setup',
    scopeNotes: 'Minimalist architecture portfolio, 3D interactive viewer mockup, project inquiry form.',
    revisionLimit: 2,
    usedRevisions: 0,
    assignedTeam: ['usr_kasun'],
    milestones: [
      {
        id: 'ms_hs_1',
        title: 'Architectural Style Guide & Wireframes',
        description: 'Typography, grid layouts, minimalist black/white styling',
        dueDate: '25 Sep 2026',
        status: 'completed',
        order: 1,
        amount: 80000,
      },
      {
        id: 'ms_hs_2',
        title: 'High-Fidelity Portfolio Prototype',
        description: 'Case study layout, interactive gallery, modal zoom',
        dueDate: '10 Oct 2026',
        status: 'in_progress',
        order: 2,
        amount: 80000,
      },
      {
        id: 'ms_hs_3',
        title: 'Final Handover & Developer Guidelines',
        description: 'Responsive specs and web export assets',
        dueDate: '20 Oct 2026',
        status: 'pending',
        order: 3,
        amount: 60000,
      },
    ],
    terms: [
      {
        id: 'trm_hs_1',
        title: 'Turnaround Time',
        clause: 'Feedback cycles must be provided within 5 business days of deliverable submission.',
        category: 'General',
        isStandard: true,
      },
    ],
  },
  {
    id: 'prj_bloom',
    workspaceId: 'ws_isaacify',
    title: 'Bloom Creative E-Commerce',
    clientId: 'cl_bloom',
    clientName: 'Amara Fernando',
    clientInitials: 'BC',
    status: 'In Progress',
    progressPercentage: 80,
    totalTasks: 15,
    completedTasks: 12,
    currentMilestone: 'Milestone 4 of 4',
    milestoneRatio: '4/4',
    dueDate: '05 Oct 2026',
    startDate: '15 Aug 2026',
    budget: 150000,
    currency: 'LKR',
    priority: 'High',
    daysLeftText: '8 days left',
    currentFocus: 'Checkout testing',
    scopeNotes: 'Fashion boutique mobile UI kit, Lookbook interactive screen, customer reviews section.',
    revisionLimit: 3,
    usedRevisions: 2,
    assignedTeam: ['usr_kasun'],
    milestones: [
      {
        id: 'ms_bc_1',
        title: 'Lookbook & Visual Tone',
        dueDate: '01 Sep 2026',
        status: 'approved',
        order: 1,
        amount: 40000,
      },
      {
        id: 'ms_bc_2',
        title: 'Mobile Shop UX',
        dueDate: '15 Sep 2026',
        status: 'approved',
        order: 2,
        amount: 50000,
      },
      {
        id: 'ms_bc_3',
        title: 'Payment & Checkout Review',
        dueDate: '28 Sep 2026',
        status: 'approved',
        order: 3,
        amount: 35000,
      },
      {
        id: 'ms_bc_4',
        title: 'Final QA & Launch Checklist',
        dueDate: '05 Oct 2026',
        status: 'in_progress',
        order: 4,
        amount: 25000,
      },
    ],
    terms: [
      {
        id: 'trm_bc_1',
        title: 'Deliverable Formats',
        clause: 'All assets will be provided in Figma, SVG vectors, and optimized PNG formats.',
        category: 'Scope & Revisions',
        isStandard: true,
      },
    ],
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'tsk_1',
    workspaceId: 'ws_isaacify',
    projectId: 'prj_ceylonbites',
    title: 'Review homepage feedback',
    projectTitle: 'CeylonBites Brand & Website',
    description: 'Address Senuri’s feedback on hero typography contrast and mobile viewport alignment for CeylonBites restaurant homepage.',
    status: 'in_progress',
    assignee: 'Kasun Alwis',
    estimatedHours: 3.5,
    scheduledTime: '9:00 AM',
    dueDate: '2026-09-30',
    completed: false,
    order: 1,
    priority: 'High',
  },
  {
    id: 'tsk_2',
    workspaceId: 'ws_isaacify',
    projectId: 'prj_harbor',
    title: 'Send project update to Shenal',
    projectTitle: 'Harbor Studio Website',
    description: 'Deliver the interactive Figma prototyping walkthrough for navigation flows and contact enquiry modal.',
    status: 'pending',
    assignee: 'Kasun Alwis',
    estimatedHours: 2.0,
    scheduledTime: '11:30 AM',
    dueDate: '2026-10-02',
    completed: false,
    order: 2,
    priority: 'Medium',
  },
  {
    id: 'tsk_3',
    workspaceId: 'ws_isaacify',
    projectId: 'prj_bloom',
    title: 'Prepare milestone 2 invoice',
    projectTitle: 'Bloom Creative E-Commerce',
    description: 'Generate commercial invoice for LKR 125,000 covering frontend React Native catalog views and Stripe integration test scripts.',
    status: 'completed',
    assignee: 'Kasun Alwis',
    estimatedHours: 1.0,
    scheduledTime: '3:00 PM',
    dueDate: '2026-10-05',
    completed: true,
    order: 3,
    priority: 'High',
  },
  {
    id: 'tsk_4',
    workspaceId: 'ws_isaacify',
    projectId: 'prj_ceylonbites',
    title: 'Implement SVG icon set',
    projectTitle: 'CeylonBites Brand & Website',
    description: 'Export 24 custom Sri Lankan culinary SVG icons with sharp vector boundaries and color token bindings.',
    status: 'in_progress',
    assignee: 'Kavindu Silva',
    estimatedHours: 4.0,
    scheduledTime: '4:30 PM',
    dueDate: '2026-10-01',
    completed: false,
    order: 4,
    priority: 'Medium',
  },
  {
    id: 'tsk_5',
    workspaceId: 'ws_isaacify',
    projectId: 'prj_harbor',
    title: 'Finalize terms & conditions draft',
    projectTitle: 'Harbor Studio Website',
    description: 'Incorporate 15-day late fee clause and copyright assignment conditions into the master contract.',
    status: 'pending',
    assignee: 'Kumuditha Perera',
    estimatedHours: 2.5,
    scheduledTime: '2:00 PM',
    dueDate: '2026-10-03',
    completed: false,
    order: 5,
    priority: 'High',
  },
];

export const INITIAL_MEETING: MeetingItem = {
  id: 'mtg_ceylonbites',
  workspaceId: 'ws_isaacify',
  projectId: 'prj_ceylonbites',
  clientId: 'cl_senuri',
  title: 'CeylonBites review',
  timeText: 'Today at 2:30 PM • Google Meet',
  platform: 'Google Meet',
  participants: 'Kasun & Senuri',
  participantInitials: ['KF', 'SP'],
  joinUrl: 'https://meet.google.com/abc-isaacify-cb',
};

export const INITIAL_DELIVERABLE: DeliverableItem = {
  id: 'del_homepage_v2',
  workspaceId: 'ws_isaacify',
  projectId: 'prj_ceylonbites',
  projectTitle: 'CeylonBites Brand & Website',
  deliverableName: 'Homepage Design • v2',
  fileName: 'Homepage-v2-final.fig',
  fileSize: '4.8 MB',
  fileType: 'Figma Design',
  version: 'v2',
  thumbnailUrl: undefined,
  author: 'Kasun',
  authorNote: 'Revised spice hero banner & CTAs based on Senuri\'s request.',
  submittedText: 'Submitted today',
  submittedAt: 'Today at 10:15 AM',
  status: 'action_required',
  history: [
    {
      version: 'v1',
      fileName: 'Homepage-v1-initial.fig',
      status: 'changes_requested',
      submittedAt: 'Yesterday at 3:15 PM',
      clientFeedback: 'Please revise spice hero banner and enhance CTA contrast.',
    },
  ],
};

export const INITIAL_INVOICE: Invoice = {
  id: 'inv_2026_014',
  workspaceId: 'ws_isaacify',
  invoiceNumber: 'INV-2026-014',
  projectId: 'prj_ceylonbites',
  projectTitle: 'CeylonBites Brand & Website',
  clientId: 'cl_senuri',
  clientName: 'Senuri Perera',
  totalAmount: 180000,
  subtotal: 180000,
  discount: 0,
  taxAmount: 0,
  taxRate: 0,
  paidAmount: 72000,
  outstandingAmount: 108000,
  currency: 'LKR',
  issueDate: '15 Sep 2026',
  dueDate: '30 Sep 2026',
  status: 'Partially Paid',
  notes: '40% initial deposit paid. Remaining 60% due upon Milestone 2 approval.',
  items: [
    {
      id: 'itm_1',
      description: 'Brand Identity & Visual Guidelines',
      quantity: 1,
      rate: 80000,
      amount: 80000,
    },
    {
      id: 'itm_2',
      description: 'Responsive E-Commerce UI/UX Design (10 screens)',
      quantity: 1,
      rate: 100000,
      amount: 100000,
    },
  ],
  payments: [
    {
      id: 'pay_1',
      amount: 72000,
      submittedAt: '2026-09-15',
      status: 'verified',
      referenceNumber: 'HNB-TXN-902148',
      verifiedAt: '2026-09-16T09:00:00Z',
    },
  ],
};

export const INITIAL_INVOICES: Invoice[] = [
  INITIAL_INVOICE,
  {
    id: 'inv_2026_015',
    workspaceId: 'ws_isaacify',
    invoiceNumber: 'INV-2026-015',
    projectId: 'prj_harbor',
    projectTitle: 'Harbor Studio Website',
    clientId: 'cl_harbor',
    clientName: 'David Lee',
    totalAmount: 140000,
    subtotal: 140000,
    discount: 0,
    taxAmount: 0,
    taxRate: 0,
    paidAmount: 0,
    outstandingAmount: 140000,
    currency: 'LKR',
    issueDate: '20 Sep 2026',
    dueDate: '15 Oct 2026',
    status: 'Sent',
    notes: 'Phase 1 architectural portfolio design and prototype retainer.',
    items: [
      {
        id: 'itm_h1',
        description: 'Architectural Style Guide & Wireframe System',
        quantity: 1,
        rate: 140000,
        amount: 140000,
      },
    ],
    payments: [],
  },
  {
    id: 'inv_2026_016',
    workspaceId: 'ws_isaacify',
    invoiceNumber: 'INV-2026-016',
    projectId: 'prj_bloom',
    projectTitle: 'Bloom Creative E-Commerce',
    clientId: 'cl_bloom',
    clientName: 'Amara Fernando',
    totalAmount: 150000,
    subtotal: 150000,
    discount: 0,
    taxAmount: 0,
    taxRate: 0,
    paidAmount: 150000,
    outstandingAmount: 0,
    currency: 'LKR',
    issueDate: '01 Sep 2026',
    dueDate: '20 Sep 2026',
    status: 'Paid',
    notes: 'Full payment cleared for Mobile Lookbook & Catalog UX Kit.',
    items: [
      {
        id: 'itm_b1',
        description: 'Complete Fashion Catalog UI Kit & Lookbook',
        quantity: 1,
        rate: 150000,
        amount: 150000,
      },
    ],
    payments: [
      {
        id: 'pay_b1',
        amount: 150000,
        submittedAt: '2026-09-18',
        status: 'verified',
        referenceNumber: 'COM-BANK-883011',
        verifiedAt: '2026-09-18T14:30:00Z',
      },
    ],
  },
];

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  {
    id: 'tx_1',
    workspaceId: 'ws_isaacify',
    invoiceId: 'inv_2026_014',
    paymentId: 'pay_1',
    source: 'payment',
    title: 'Payment · CeylonBites Spices',
    subtitle: 'INV-2026-014',
    amount: 72000,
    type: 'income',
    currency: 'LKR',
    category: 'Client payment',
    date: '2026-09-15',
    occurredAt: '2026-09-15T10:30:00Z',
  },
  {
    id: 'tx_2',
    workspaceId: 'ws_isaacify',
    invoiceId: 'inv_2026_016',
    paymentId: 'pay_b1',
    source: 'payment',
    title: 'Payment · Bloom Creative',
    subtitle: 'INV-2026-016',
    amount: 150000,
    type: 'income',
    currency: 'LKR',
    category: 'Client payment',
    date: '2026-09-18',
    occurredAt: '2026-09-18T14:30:00Z',
  },
  {
    id: 'tx_3',
    workspaceId: 'ws_isaacify',
    source: 'expense',
    title: 'Figma Professional & Adobe CC',
    subtitle: 'Monthly Design Subscriptions',
    amount: 18500,
    type: 'expense',
    currency: 'LKR',
    category: 'Software & Tools',
    date: '2026-09-05',
    occurredAt: '2026-09-05T08:00:00Z',
  },
  {
    id: 'tx_4',
    workspaceId: 'ws_isaacify',
    source: 'expense',
    title: 'Stock Photo & Font Licensing',
    subtitle: 'Spice texture assets',
    amount: 9500,
    type: 'expense',
    currency: 'LKR',
    category: 'Project Assets',
    date: '2026-09-12',
    occurredAt: '2026-09-12T16:00:00Z',
  },
];

export const INITIAL_RECENT_ACTIVITY: RecentActivityItem[] = [
  {
    id: 'act_1',
    title: 'Kasun shared Homepage-v2.pdf',
    authorName: 'Kasun',
    fileName: 'Homepage-v2.pdf',
    fileSize: '2.4 MB',
    timeAgo: '2 hours ago',
    type: 'pdf',
  },
  {
    id: 'act_2',
    title: 'Senuri reviewed Homepage v2',
    authorName: 'Senuri Perera',
    fileName: 'Feedback Notes',
    fileSize: '12 KB',
    timeAgo: '4 hours ago',
    type: 'pdf',
  },
  {
    id: 'act_3',
    title: 'INV-2026-014 deposit verified',
    authorName: 'System',
    fileName: 'Receipt-72000.pdf',
    fileSize: '150 KB',
    timeAgo: 'Yesterday',
    type: 'pdf',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    workspaceId: 'ws_isaacify',
    title: 'Homepage feedback',
    message: 'Senuri Perera added 3 notes on CeylonBites homepage.',
    timeAgo: '15m ago',
    unread: true,
    type: 'deliverable',
  },
  {
    id: 'notif_2',
    workspaceId: 'ws_isaacify',
    title: 'Payment Verified',
    message: 'Deposit of LKR 72,000 for INV-2026-014 verified.',
    timeAgo: '2h ago',
    unread: false,
    type: 'payment',
  },
  {
    id: 'notif_3',
    workspaceId: 'ws_isaacify',
    title: 'Scope Change Requested',
    message: 'Senuri Perera requested UK multi-currency support on CeylonBites.',
    timeAgo: '1d ago',
    unread: true,
    type: 'scope',
  },
];

export const INITIAL_REMINDERS: ReminderItem[] = [
  {
    id: 'rem_1',
    workspaceId: 'ws_isaacify',
    title: 'Review CeylonBites Homepage v2',
    dateTime: '2026-10-10T14:00:00.000Z',
    status: 'pending',
    linkedType: 'project',
    linkedId: 'prj_ceylonbites',
    linkedTitle: 'CeylonBites Brand & Website',
    priority: 'high',
    notify: true,
    type: 'project',
    createdAt: '2026-09-16T10:00:00.000Z',
  },
  {
    id: 'rem_2',
    workspaceId: 'ws_isaacify',
    title: 'Issue Milestone 2 Invoice to Senuri',
    dateTime: '2026-10-12T10:00:00.000Z',
    status: 'pending',
    linkedType: 'invoice',
    linkedId: 'inv_2026_014',
    linkedTitle: 'INV-2026-014 (CeylonBites)',
    priority: 'medium',
    notify: true,
    type: 'invoice',
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'rem_3',
    workspaceId: 'ws_isaacify',
    title: 'Follow up on Harbor Studio wireframes',
    dateTime: '2026-10-15T09:30:00.000Z',
    status: 'pending',
    linkedType: 'project',
    linkedId: 'prj_harbor',
    linkedTitle: 'Harbor Studio Website',
    priority: 'medium',
    notify: false,
    type: 'project',
    createdAt: '2026-09-20T10:00:00.000Z',
  },
];
