export const colors = {
  background: '#FAF9FD',
  white: '#FFFFFF',
  textPrimary: '#18181B',
  textSecondary: '#6B6875',
  textMuted: '#9CA3AF',
  primary: '#7547DB',
  primaryDark: '#5F3FAF',
  primaryMedium: '#7050C4',
  primaryLight: '#8B69E8',
  primaryTopTip: '#9A7AF1',
  primaryLeftFacet: '#6546B6',
  buttonPrimary: '#6D4BCB',
  buttonPrimaryPressed: '#5C3CB3',
  primarySoft: '#F1EAFD',
  loadingDots: '#9B82D7',
  glowCenter: '#EDE5F8',
  cardBorder: '#E5E7EB',
  cardBorderSelected: '#6D4BCB',
  cardBackground: '#FFFFFF',
  cardBackgroundSelected: '#F3F0FD',
  inputBorder: '#E5E7EB',
  inputBorderFocused: '#6D4BCB',
  inputBackground: '#FFFFFF',
  progressBarActive: '#6D4BCB',
  progressBarInactive: '#E5E7EB',
  badgeBackground: '#F3F0FD',
  badgeText: '#6D4BCB',
  iconBackgroundDefault: '#F4F4F6',
  iconColorDefault: '#4B5563',
  chatBlue: '#3B82F6',
  statusGreen: '#10B981',
  pillPurpleBg: '#F1EAFD',
  pillPurpleText: '#6D4BCB',
  pillPeachBg: '#FEF3E8',
  pillPeachText: '#B45309',
  badgeRedBg: '#FEF2F2',
  badgeRedText: '#DC2626',
  error: '#DC2626',
  greySurface: '#F9FAFB',
} as const;

export type Colors = typeof colors;
